### ISSUE TITLE
An extra 'end' is created for 'elseif'

### ISSUE THREAD

**Issue by wyozi** [FPtje/Sublime-GLua-Highlight#13]
```lua
if x then
elseif y then
end
end
```

Both ```end```s were created by sublime. Would it be possible to not create it for statements beginning with elseif or else.

**Comment by FPtje** [comment]
The snippet is on the word "then". When the snippet is triggered, it doesn't know whether you're in the then of an `if` or `elseif`. It acts the same twice. I don't see a way of realistically solving this.

I'll close the issue, but do you have any ideas what I can do?

**Comment by wyozi** [comment]
Ahh, I did not know sublimetext snippets do not take regexps, which is how I remember solving a similar problem for Atom.

Oh well, maybe one day they will be supported.
