### ISSUE TITLE
Code visual studio generator

### ISSUE THREAD

**Issue by thegrb93** [FPtje/Sublime-GLua-Highlight#15]
Someone brought up this new editor which seems to be much awesomer than sublime. The linting plugins are in javascript though. Maybe you could adapt your generator to make a glua plugin for this? https://code.visualstudio.com/

The existing plugin for lua is found here. AppData\Local\Code\app-0.1.0\resources\app\plugins\vs.language.lua\luaDef.js 
I could try if you don't feel like it. Let me know.

**Comment by FPtje** [comment]
Beyond the scope of this project. Sorry.

**Comment by thegrb93** [comment]
I'll try then.
