### ISSUE TITLE
NULL has no colour

### ISSUE THREAD

**Issue by BillyOnWiiUIn144p** [FPtje/Sublime-GLua-Highlight#19]
The global variable "NULL" appears to have no colour/syntax.
Maybe this is a "feature", but I'm not sure.
Maybe if could have the same colour and syntax as nil?
Might want to check up on these if you missed any, too:
http://wiki.garrysmod.com/page/Global_Variables

**Comment by FPtje** [comment]
I remember `NULL` having a colour. Weird that it didn't anymore.
