### ISSUE TITLE
concommand.Add autocompletion appears to "complete" something else

### ISSUE THREAD

**Issue by BillyOnWiiUIn144p** [FPtje/Sublime-GLua-Highlight#25]
![](http://i.imgur.com/oBBMwvC.png)

**Comment by FPtje** [comment]
Make sure to autocomplete before you type the `.`. Then it will work fine. Sublime thinks you start a new word when you type a `.`. `Add` is a valid method of textures or something and is thus suggested.

It's really annoying, but I don't see any way of changing this.

**Comment by BillyOnWiiUIn144p** [comment]
No problem, thanks.
