### ISSUE TITLE
RENDERGROUP_OPAQUE not highlighted

### ISSUE THREAD

**Issue by Bo98** [FPtje/Sublime-GLua-Highlight#27]
```
... RENDERGROUP_(OPAQUE_(HUGE|BRUSH) ...
```

Looks like that should be:

```
... RENDERGROUP_(OPAQUE(|_HUGE|_BRUSH) ...
```

**Comment by Bo98** [comment]
Happens for this enum and not something like `RENDERGROUP_STATIC` (where there's `RENDERGROUP_STATIC_HUGE` but not `RENDERGROUP_STATIC_BRUSH`), because of this really weird logic:

https://github.com/FPtje/Sublime-GLua-Highlight/blob/master/GENERATOR/SublimeText/lua/autorun/MatchGenerator.lua#L298-L301

**Comment by FPtje** [comment]
There was no indication whether a sub-enum was an enum of itself. That is now stored in the internal representation.

this is what I get now:
```
RENDERGROUP_(OPAQUE(|_(HUGE|BRUSH))|VIEWMODEL(|_TRANSLUCENT)|BOTH|OTHER|TRANSLUCENT|STATIC(|_HUGE))
```

**Comment by Bo98** [comment]
LGTM
