### ISSUE TITLE
Enums don't autocomplete

### ISSUE THREAD

**Issue by Bo98** [FPtje/Sublime-GLua-Highlight#29]
It used to before it was revamped.

**Comment by FPtje** [comment]
![sublime_text_2016-02-27_19-45-26](https://cloud.githubusercontent.com/assets/1202014/13374627/b0e4e26a-dd8a-11e5-8197-10e425b813bc.png)

**Comment by FPtje** [comment]
oh autocomplete. I only changed highlighting.

**Comment by FPtje** [comment]
Quite frankly I don't know what made sublime autocomplete them in the first place.

**Comment by Bo98** [comment]
3b72225

**Comment by FPtje** [comment]
But then you're talking about stuff from over a year ago. Are you not talking about the updates I just made? The autocompletions file is now generated from the wiki.

**Comment by FPtje** [comment]
https://github.com/JohnnyCrazy/glua-scrapper
