### ISSUE TITLE
Odd automatic indentation with "end)"

### ISSUE THREAD

**Issue by zerfgog** [FPtje/Sublime-GLua-Highlight#32]
Here's an image:
![](http://i.imgur.com/3P3KIEa.gif)
I start with poorly indented code, then select all and use the `reindent` sublime command to fix the indentation. Note that the closure's `end)` is not indented properly.

Here's another example, nested inside a function this time:
![](http://i.imgur.com/yxYqIjR.gif)

**Comment by FPtje** [comment]
Let's hope this doesn't cause freak issues.
