### ISSUE TITLE
Not taking variables for autocomplete.

### ISSUE THREAD

**Issue by Luka2477** [FPtje/Sublime-GLua-Highlight#34]
If i write this `local HelloImAVariable = 1`, the glua will not take the variable (or if it was a function) into consideration when typing it somewhere else in the code. Either is it highlighted. Typing helloima will give no autocomplete options. Please comment back if you have seen this, and are willing to fix it :) This is a big con rigth now.

**Comment by FPtje** [comment]
![sublime_text_2017-08-22_21-51-08](https://user-images.githubusercontent.com/1202014/29584449-0a36076e-8784-11e7-9823-4c7f60c25658.png)
Not sure what you mean

**Comment by Luka2477** [comment]
![skaermbillede 7](https://user-images.githubusercontent.com/25512917/29584703-ddd0fe94-8784-11e7-8a69-3767bf145b38.png)
It doesnt happen for me
