### ISSUE TITLE
Pretty Print Not working

### ISSUE THREAD

**Issue by RadioactvePixels** [FPtje/Sublime-GLua-Highlight#40]
Not sure if I'm not using it right, but when I try to press CTRL + SHIFT + P then type Pretty Print and hit enter, It doesn't change the code at all. Am I doing something wrong?

**Comment by FPtje** [comment]
That's part of the glualint package, not the highlighter. If you have that installed as well, make sure the executable is in your PATH, and that the keyboard shortcut is correct.
