### ISSUE TITLE
Some entries are not highlighted

### ISSUE THREAD

**Issue by dvdvideo1234** [FPtje/Sublime-GLua-Highlight#44]
![image](https://user-images.githubusercontent.com/9112662/67075571-1fa6f500-f194-11e9-8880-53f070ca6137.png)

**Comment by dvdvideo1234** [comment]
Sublime version: 3.2.2 Build 3211
Package version: 2019.07.22.19.47.24

**Comment by FPtje** [comment]
Things added in updates I suppose?

**Comment by djtb2924** [comment]
I’m gonna recrawl this evening

**Comment by FPtje** [comment]
@djtb2924 Did you have any success?

**Comment by djtb2924** [comment]
Yes but I went to holidays, it will ne complicated to do that before 1 week
