### ISSUE TITLE
elseif ... then will autocomplete an end

### ISSUE THREAD

**Issue by KillingTorcher** [FPtje/Sublime-GLua-Highlight#49]
If I had any clue how the snippet content syntax worked I'd suggest a solution. Possibly regex if they allow it?

Anyway, end should only be autocompleted on regular ifs.

Otherwise we end up with code such as:

```Lua
if condition then
    print("condition")
elseif othercondition then
    print("othercondition")
end
end
```

Thus requiring the deletion of the extraneous end.

**Comment by FPtje** [comment]
Yeah, that's because the snippet fires on just the word `then`. They now trigger on the words `if` and `elseif`. That requires a bit of getting used to, but it shouldn't misfire.
