### ISSUE TITLE
Multiliner highliting

### ISSUE THREAD

**Issue by dvdvideo1234** [FPtje/Sublime-GLua-Highlight#55]
function are not being highlighted when being spit to multi-line:
```lua
  function LaserLib.DoDamage(target  , laser , attacker, origin ,
                             normal  , direct, damage  , force  ,
                             dissolve, noise , fcenter , safety)
  end
```
However it is being highlighted when I place a `)` at the end of the line where the `function` keyword is located:
![image](https://github.com/FPtje/Sublime-GLua-Highlight/assets/9112662/b8f1abbb-82a0-4f67-bfef-2aaf2cc7a0e1)

Is it also possible for the word list to be updated with the recent Game APPI updates

**Comment by FPtje** [comment]
I'm afraid I haven't used Sublime text for quite a few years now. That combined with how little GMod I play, the cost to maintain this code is too high for me. That means I will not be solving this issue, my apologies.

I'll update the README to make this clear.
